base_url = "https://zola-mikoto.netlify.com/"
title = "mikoto theme"
description = ""
compile_sass = true
slugify-path = true
highlight_code = true
highlight_theme = "monokai"
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
    {name = "series", rss = true},
]



# theme = "mikoto"
extra_syntaxes = ["syntaxes"]



[extra]
author = "Aster"
mikoto_title = "Mikoto"
mikoto_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/series", name = "Series"},
    {url = "$BASE_URL/about", name = "About"},
]
favicon = ""
github_link = "https://github.com/GalAster/zola-theme-mikoto"

# comment `enable` to close the plugin

aplayer_enable = true
aplayer_cdn_js = ""
aplayer_cdn_css = ""
aplayer_cdn_meting = ""
aplayer_background = true
aplayer_background_server = "netease"
aplayer_background_type = "album"
aplayer_background_id = "82260016"

live2d_enbale = true
live2d_cdn = ""

mathjax_enable = true
mathjax_cdn = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
katex_enalbe = true
katex_cdn = "https://cdn.jsdelivr.net/npm/katex@latest"


font_awesome_cdn = ""
