[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.11.0"
DEPLOY_PRIME_URL = "https://zola-mikoto.netlify.com/"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"